# Generated by Django 5.0.4 on 2024-04-23 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentandShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.BigIntegerField()),
                ('transaction_passed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('items_bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cartitem')),
                ('shippingaddress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.address')),
            ],
        ),
    ]
