# Generated by Django 5.0.4 on 2024-04-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_paymentandshipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='paymentandshipping',
            name='items_bought',
        ),
        migrations.AddField(
            model_name='paymentandshipping',
            name='items_bought',
            field=models.ManyToManyField(to='app.cartitem'),
        ),
    ]
