# Generated by Django 5.0.4 on 2024-05-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_paymentandshipping2_delete_paymentandshipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentandshipping2',
            name='item_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paymentandshipping2',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
