apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-django-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-django
  template:
    metadata:
      labels:
        app: python-django
    spec:
      containers:
      - name: python-django
        image: gcr.io/PROJECT_ID/python-django2:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "YOUR_SECRET_KEY_HERE"
        - name: DEBUG
          value: "False"
        - name: DB_NAME
          value: "your_db_name"
        - name: DB_USER
          value: "your_db_user"
        - name: DB_PASSWORD
          value: "your_db_password"
        - name: DB_HOST
          value: "your_db_host"
        - name: DB_PORT
          value: "your_db_port"